# Generated by Django 4.2.4 on 2023-08-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0002_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='drink_images/')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='staff_images/')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('visiting_datetime', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.staffmember')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('serve_datetime', models.DateTimeField(auto_now_add=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.drink')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.visitor')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.AddField(
            model_name='drink',
            name='serve_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.staffmember'),
        ),
    ]
